# Generated by Django 5.2.16 on 2026-07-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side ingestion time (UTC). Indexed for range scans.')),
                ('temperature', models.FloatField(help_text='Ambient temperature in degrees Celsius.')),
                ('humidity', models.FloatField(help_text='Relative humidity in percent.')),
                ('ammonia_level', models.FloatField(help_text='NH3 concentration in PPM.')),
                ('predicted_class', models.CharField(choices=[('CRITICAL_AMMONIA', 'Critical Ammonia'), ('HEAT_STRESS_WARNING', 'Heat Stress Warning'), ('LOW_TEMP_ALERT', 'Low Temperature Alert'), ('OPTIMAL_ENVIRONMENT', 'Optimal Environment')], help_text='Server-computed environmental classification at ingestion time.', max_length=32)),
            ],
            options={
                'verbose_name': 'Poultry telemetry record',
                'verbose_name_plural': 'Poultry telemetry records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
