# Generated by Django 5.2.16 on 2026-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrytelemetry',
            name='predicted_ammonia',
            field=models.FloatField(blank=True, help_text='ESP32-S3 Edge-AI NH3 forecast in PPM. Null until hardware is linked.', null=True),
        ),
        migrations.AddField(
            model_name='poultrytelemetry',
            name='predicted_temperature',
            field=models.FloatField(blank=True, help_text='ESP32-S3 Edge-AI temperature forecast in degrees Celsius. Null until hardware is linked.', null=True),
        ),
    ]
