# Generated by Django 5.2.16 on 2026-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_poultrytelemetry_predicted_ammonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrytelemetry',
            name='predicted_spike_probability',
            field=models.FloatField(blank=True, help_text='Master-node TFLite Micro classifier output in [0, 1]: probability of an imminent ammonia spike, computed from a rolling window of sensor-node readings relayed over ESP-NOW. Null until the ESP32-S3 master is linked.', null=True),
        ),
    ]
