# Generated by Django 5.2.16 on 2026-07-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_poultrytelemetry_predicted_spike_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_configured', models.BooleanField(default=False, help_text="False until a user has saved a profile from the dashboard; while false, ingestion uses the classifier's fixed defaults.")),
                ('age_weeks', models.PositiveSmallIntegerField(default=1, help_text='Current flock age in weeks. Drives the age-appropriate temperature band (Table 4-2) unless custom thresholds are enabled.')),
                ('use_custom_thresholds', models.BooleanField(default=False, help_text='When true, the custom_* fields below override the age-derived temperature band and the default ammonia critical threshold.')),
                ('custom_temp_min_c', models.FloatField(blank=True, help_text='Custom low-temperature alert threshold in degrees Celsius.', null=True)),
                ('custom_temp_max_c', models.FloatField(blank=True, help_text='Custom heat-stress temperature threshold in degrees Celsius (paired with the fixed >70% humidity conjunction).', null=True)),
                ('custom_ammonia_critical_ppm', models.FloatField(blank=True, help_text="Custom ammonia critical threshold in PPM, overriding the classifier's 25.0 ppm default.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flock profile',
                'verbose_name_plural': 'Flock profile',
            },
        ),
    ]
