# Generated by Django 5.2.16 on 2026-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_flockprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', 'Automatic (classifier-driven)'), ('MANUAL', 'Manual override')], default='AUTO', help_text='AUTO derives fan/heater duty from the latest classification; MANUAL uses the fields below.', max_length=8)),
                ('fan_speed_pct', models.PositiveSmallIntegerField(default=0, help_text='Manual fan speed, 0-100%. Only applied while mode=MANUAL.')),
                ('heater_power_pct', models.PositiveSmallIntegerField(default=0, help_text='Manual PTC heater power, 0-100%. Only applied while mode=MANUAL.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actuator control',
                'verbose_name_plural': 'Actuator control',
            },
        ),
    ]
