# Generated by Django 5.2.16 on 2026-08-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_actuatorcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuatorcontrol',
            name='heater_power_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text="Manual heater state, 0 (off) or 100 (on) only -- the heater is a relay switch, not PWM, so there's no variable power in between. Only applied while mode=MANUAL."),
        ),
    ]
