# Generated by Django 5.2.16 on 2026-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_alter_actuatorcontrol_heater_power_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuatorcontrol',
            name='fan_speed_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text="Manual fan speed, 0-100%. Only applied while mode=MANUAL, and even then only up until a live reading crosses a safety threshold (critical ammonia or heat stress) -- see effective_duty()'s safety floor, which overrides this."),
        ),
        migrations.AlterField(
            model_name='actuatorcontrol',
            name='heater_power_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text="Manual heater state, 0 (off) or 100 (on) only -- the heater is a relay switch, not PWM, so there's no variable power in between. Only applied while mode=MANUAL, and even then only up until a live reading crosses a safety threshold (genuine cold forces it on, heat stress forces it off) -- see effective_duty()'s safety floor, which overrides this."),
        ),
        migrations.AlterField(
            model_name='flockprofile',
            name='custom_ammonia_critical_ppm',
            field=models.FloatField(blank=True, help_text="Custom ammonia critical threshold in PPM, overriding the classifier's 15.0 ppm default.", null=True),
        ),
    ]
