# Generated by Django 5.2.16 on 2026-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_alter_help_text_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrytelemetry',
            name='model_seconds_to_next',
            field=models.PositiveIntegerField(blank=True, help_text="Seconds until the master node's on-device model produces its next prediction, as reported by the master at transmission time. Covers both the initial ~70-minute warm-up and every ~10-minute refresh after. Null until the ESP32-S3 master is linked.", null=True),
        ),
    ]
